package(default_visibility = ["//visibility:public"])

cc_library(
    name = "utils",
    srcs = ["src/graph.cc"],
    hdrs = ["src/graph.h"],
    deps = [
            "@org_tensorflow//tensorflow/core:tensorflow",
            "@org_tensorflow//tensorflow/cc:client_session"
    ],
)
