package(default_visibility = ["//visibility:public"])

load("//powerspikegg:powerspikegg.bzl", "psgg_proto_library")
load("@io_bazel_rules_go//proto:go_proto_library.bzl", "go_proto_library")

psgg_proto_library(
    name = "leagueoflegends",
    srcs = glob(["*.proto"]),
)
