#
# Aliases to docker rules
#

alias(
    name = "fetcher",
    actual = "//powerspikegg/rawdata/fetcher:docker",
)

alias(
    name = "mongod",
    actual = "//third_party/mongod:docker",
)

alias(
    name = "frontend",
    actual = "//powerspikegg/frontend:docker",
)
